### ISSUE TITLE
Update from 0.1.2 to 0.1.3 does not work

### ISSUE THREAD

**Issue by derpicknicker1** [jasiek/OctoPrint-Cost#10]
Octoprint software update does not find the newes release 0.1.3
When i uninstall the plugin and reinstall it, the 0.1.3 will be installed fine.
It also misses in the releases overview https://github.com/jasiek/OctoPrint-Cost/releases
Maybe there is something messed up?

**Comment by foosel** [comment]
That it's missing in the releases here on Github is the likely cause - OctoPrint checks github releases for new entries. No new entry here - no notification that an update is available. What confuses me though is that it also is not picking up any of the other releases. I thought Github would also provide plain tags there, but maybe it doesn't and you need to create an actual release there from the tags (and add a tag for 0.1.3) @jasiek.

**Comment by jasiek** [comment]
Will do in a minute.

**Comment by jasiek** [comment]
I've tagged master as 0.1.3. Let's see if this helps.

**Comment by foosel** [comment]
Nope, it doesn't, at least not on my end:

![image](https://user-images.githubusercontent.com/83657/28157254-2e8c3ff4-67b6-11e7-8014-aa90dd54761e.png)

You'll need to create a release entry for your tags as well:

![create_github_release](https://user-images.githubusercontent.com/83657/28157338-77309afc-67b6-11e7-9620-e5d8294088bb.gif)

**Comment by jasiek** [comment]
OK, done - let me know if this works.

**Comment by foosel** [comment]
![image](https://user-images.githubusercontent.com/83657/28162539-b8830dbc-67c7-11e7-9121-73172bd72b04.png)

More or less. You might want to use the version number as release title or stuff will look a bit funny ;)

**Comment by jasiek** [comment]
Ah yes. :)
