### ISSUE TITLE
Octopi 1.3.3 RC breaks Octoprint-Cost

### ISSUE THREAD

**Issue by brianhanifin** [jasiek/OctoPrint-Cost#8]
Your plugin stopped displaying a cost estimate when I started installing the 1.3.3 release candidates. I forget whether it started on RC1 or RC2, but it persists on RC3.

I cannot find any errors in octoprint.log, only the line where it loads (the next line is another plugin loading).

`|  Cost Plugin (0.1.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_cost
`

I have also [supplied feedback on the RC Feedback discussion](https://github.com/foosel/OctoPrint/issues/1935#issuecomment-304526441) on the Octoprint github.

**Comment by foosel** [comment]
Just a quick heads-up from my side (also commented on the feedback thread as referred to above), I cannot reproduce this myself. Cost Plugin version 0.1.3, OctoPrint 1.3.3rc3:

![image](https://cloud.githubusercontent.com/assets/83657/26549064/772be168-4477-11e7-87f4-5608508cb028.png)

Freshly uploaded and analysed file (and also no problem with existing files).

**Comment by brianhanifin** [comment]
I disabled a couple of plugins, and it started working. Then I tried to renable a couple of plugins at a time and I couldn't get it to fail.

I am starting to think I only noticed it when I was printing something small enough the price wasn't over 1 cent. I am going to close this.
